"""initial_schema

Revision ID: c3e8b00884a2
Revises: 
Create Date: 2026-08-30 00:46:01.117490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.db


# revision identifiers, used by Alembic.
revision: str = 'c3e8b00884a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_interventions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_intervention_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('transactions',
    sa.Column('id', app.models.db.GUID(), nullable=False),
    sa.Column('razorpay_entity_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('payment', 'subscription', 'invoice', name='entitytype'), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('status', sa.Enum('failed', 'pending', 'recovering', 'recovered', 'escalated', name='transactionstatus'), server_default='failed', nullable=False),
    sa.Column('razorpay_error_code', sa.String(length=255), nullable=True),
    sa.Column('razorpay_error_reason', sa.String(length=255), nullable=True),
    sa.Column('razorpay_error_source', sa.String(length=255), nullable=True),
    sa.Column('razorpay_error_step', sa.String(length=255), nullable=True),
    sa.Column('raw_webhook_payload', sa.JSON(), nullable=True),
    sa.Column('recovery_link_id', sa.String(length=255), nullable=True),
    sa.Column('recovery_link_url', sa.Text(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_razorpay_entity_id'), 'transactions', ['razorpay_entity_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', app.models.db.GUID(), nullable=False),
    sa.Column('transaction_id', app.models.db.GUID(), nullable=False),
    sa.Column('agent_diagnosis', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=100), nullable=True),
    sa.Column('suggested_action', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('policy_gate_status', sa.Enum('passed', 'blocked_intervention_cap', 'blocked_low_confidence', 'blocked_manual_review', name='policygatestatus'), nullable=True),
    sa.Column('final_action', sa.String(length=100), nullable=True),
    sa.Column('action_result', sa.JSON(), nullable=True),
    sa.Column('amount_recovered_paise', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_transaction_id'), 'audit_log', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_transaction_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_transactions_razorpay_entity_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('customers')
    # ### end Alembic commands ###
